preserve_hierarchy: true
files:
  - source: /src/main/resources/assets/wallets/lang/en_us.json
    translation: /src/main/resources/assets/wallets/lang/%locale_with_underscore%.json
    dest: /src/main/resources/assets/wallets/lang/%file_name%.json