modLoader="javafml"
loaderVersion= "${loader_version_range}"
license= "${mod_license}"
issueTrackerURL = "${mod_issue_tracker_url}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="Cheaterpaul, 1LiterZinalco"
credits='''\n
- Random (textures)
- Grid (textures)'''
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
