modLoader="javafml"
loaderVersion="[46,)"
license="LGPL-3.0"
issueTrackerURL = "https://github.com/Cheaterpaul/Wallets/issues"
[[mods]]
modId="wallets"
version="${version}"
displayName="Wallets"
logoFile="logo.png"
authors="Cheaterpaul, 1LiterZinalco"
credits="Random (textures)"
description='''
This mod add 2 item:

Coins of different value and a wallet to store coins easily.
'''
[[dependencies.wallets]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wallets]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version},)"
    ordering="NONE"
    side="BOTH"
