name: Crowdin Upload

on:
  push:
    branches:
      - 1.16
      - 1.18
      - 1.19
    paths:
      - 'src/main/resources/assets/wallets/lang/en_us.json'

jobs:
  upload-source-files:
    name: Upload Source Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Crowdin Upload
        uses: crowdin/github-action@1.4.14
        with:
          upload_sources: true
          upload_language: 'en'
          auto_approve_imported: true
          add_crowdin_branch: ${{ github.ref_name }}
          crowdin_branch_name: ${{ github.ref_name }}
          config: ./crowdin.yml
          project_id: 492617
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: walletsmc
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
